<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

# Artificial Intelligence - MSc

## CS6512 - AI & Data Science Ecosystems - Theory and Practice
## SEM2 2024/5

### CS6512 Assignment 1 
#### - Linear and Nonlinear Programming
#### - Hyperparameter Optimization

### Instructor: Emil Vassev
April 2nd, 2025
<br><br>
Copyright (C) 2023-2025 - All rights reserved, do not copy or distribute without permission of the author.
***

## Submission Info
### Student Name: <span style="color:red">Sean</span>
### Student Surname: <span style="color:red">Noonan</span>
### Student ID: <span style="color:red">23300159</span>
### Date of Final Submission: <span style="color:red">11/04/25</span>
***

# Task #1: Linear and Nonlinear Programming (50%)
In this task, you are asked to determine the components of a linear/non-linear programming problem, and then to implement in Python a program that will solve that problem by using the <b>scipy.optimize</b> library. Please, consult the lectures of Week #10 for more details on how we determine the components of a linear/non-linear programming problem and also, how we implement linear/non-linear programs in Python. The program you are going to implement is based on a real-life scenario, which is invented by the author of this assignment and thus, the numbers provided are fictive.
## The real-life scenario
Mazda Motor Corporation produces three models of its CX series: Mazda CX-3, Mazda CX-5, and Mazda CX-9 (for simplicity, in this scenario we ignore the new models like CX-30, CX-50, etc.). Market projections indicate an expected monthly demand of at least: 3500 cars of the CX-3 model, 5000 cars of the CX-5 model, and 2100 cars of the CX-9 model.  Due to insufficient production capacity, no more than 4000 cars can be made of model CX-3, no more than 7000 cars can be made of model CX-5, and no more than 2500 cars can be made of model CX-9. Due to existing contracts with car dealers worldwide, a total of at least 12000 cars must be produced each month. Here is the financial result calculated as production costs – selling costs per model: 
<li>CX-3: EUR 3400 profit</li> 
<li>CX-5: EUR 2500 loss</li>
<li>CX-9: EUR 7200 profit</li>
<br>
How many cars of each Mazda CX model should be produced monthly, so to maximize the total net profit?  
<br><br>
<span style="color:blue">The author of this assignment drives Mazda CX-5, 2021, and he loves it! He is convinced this car is undervalued. :)</span>

## Here are the steps you need to follow:

## Step 1: Determine the programming problem: linear or non-linear.  (2%)

<span style="color:red">TODO: your rationale goes here</span>

This is a linear programming problem. The contraint inequalities/equations and objective function are linear functions.

## Step 2: Define the components of the LPP/NLPP tuple  <D, f, Fc , C, Cn, R, Tc>. (23%)

### Step 2.1: D - Decision Variables (2%)

<span style="color:red">TODO: your description goes here</span>
#### Assumptions 
**Decision variables:**
* `x` - the number of units of CX-3 produced in the current month
* `y` - the number of units of CX-5 produced in the current month
* `z` - the number of units of CX-9 produced in the current month

* $D$ *decision variables* - `D={x, y, z}`

### Step 2.2: f - Objective Function (10%)

<span style="color:red">TODO: your description goes here</span>
**Objective function:**
* the objective is to maximize the profit
* `max[p], p = x*3400 + y*(-2500) + z*7200`

### Step 2.3: Fc - Objective Function Coefficients (2%)

<span style="color:red">TODO: your description goes here</span>

3400,-2500,7200

* $F_{c}$ *objective function coefficients* - `Fc = {3400:x, -2500:y, 7200:z}`

### Step 2.4: C - Constraints (5%)

<span style="color:red">TODO: your description goes here</span>
**Constraints:**
* `x >= 3500`
* `y >= 5000`
* `z >= 2100`

* `x <= 4000`
* `y <= 7000`
* `z <= 2500`

* `x + y + z >= 12000`

* $C$ *constraints* -  `C = {(3500 ≤ x ≤ 4000), (5000 ≤ x ≤ 7000), (2100 ≤ x ≤ 2500)}`

### Step 2.5: Cn – Non-negative Constraints (1%)

<span style="color:red">TODO: your description goes here</span>

* `x >= 0`
* `y >= 0`
* `z >= 0`

* $C_{n}$ *non-negative constraints* - `Cn = {x≥0, y≥0, z≥0}`

### Step 2.6: R – Resource Availability (1%)

<span style="color:red">TODO: your description goes here</span>

{3500,
5000,
2100,
4000,
7000,
2500,
12000}

* $R$ *resource availability* - `R = {3500,5000,2100,4000,7000,2500,12000}`

### Step 2.7: Tc – Technological Coefficients (2%)

<span style="color:red">TODO: your description goes here</span>
(1,1,1)

* $T_{c}$ *technological coefficients* - `Tc = {1, 0, 0, 0, 1, 0, 0, 0, 1, -1, -1, -1}`

## Step 3: Implement the LPP/NLPP in Python by using scipy.optimize as shown in the lectures. (25%)

Use the <b>scipy.optimize</b> library to implement a program that will solve the linear/non-linear programming problem specified in Step 2.

### Step 3.1: Implement the programming model. (20%)

In [1]:
# your code goes here
from scipy.optimize import linprog

### Step 3.2: Execute the programming model. (4%)

**Transformations**:
* Objective function - instead of maximizing we will minimize its negative form.
    * `max[p], -p = x*(-3400) + y*(+2500) + z*(-7200)`

In [ ]:
# your code goes here
# Change t minimisation problem
obj = [-3400, 2500, -7200]
#      ─┬  ─┬ ┬-| Coefficient for z
#       │   └┤ Coefficient for y
#       └────┤ Coefficient for x

lhs_ineq = [
    [1, 0, 0],  # x1 <= 4000
    [0, 1, 0],  # x2 <= 7000
    [0, 0, 1],  # x3 <= 2500
    [-1, -1, -1]]  # x1 + x2 + x3 >= 12000 (we negate this for <= form)

rhs_ineq = [4000, 7000, 2500,-12000]  # Yellow constraint right side

In [ ]:
bnd = [(3500, 4000),  # Bounds of x
       (5000, 7000),  # Bounds of y 
       (2100, 2500)]  # Bounds of z

In [ ]:
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, bounds=bnd,
              method='highs')

### Step 3.3: Show the result of your program's execution. (1%)

In [ ]:
# your code goes here

In [ ]:
opt

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -17850000.0
              x: [ 4.000e+03  5.500e+03  2.500e+03]
            nit: 0
          lower:  residual: [ 5.000e+02  5.000e+02  4.000e+02]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [ 0.000e+00  1.500e+03  0.000e+00]
                 marginals: [-5.900e+03  0.000e+00 -9.700e+03]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.500e+03  0.000e+00  0.000e+00]
                 marginals: [-0.000e+00 -0.000e+00 -0.000e+00 -2.500e+03]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

There fore to maximise profit and make 17.85 million, we should build:

*  4000 units of CX-3 monthly
*  5500 units of CX-5 produced in the current month
*  2500 units of CX-9 produced in the current month

# Task #2: Hyperparameter Optimization (50%)

## Optimization Problem
In this task, you are asked to work on a supervised ML problem to predict prices and optimize this prediction by adjusting the hyperparameters in order to minimize the cost function. 

## Grid Search
In this task, you are asked to use Grid Search, which is an Exhaustive Search through a manually specified subset of hyperparameters of a learning algorithm. It defines the search space as a grid of hyperparameter values and evaluates every position in the grid search space.

## Data
The example data we are going to use for Exhaustive Search Optimization is a real-life data provide by the **seaborn** database. The dataset is "diamonds" and the "price" is the target.

## Load, Evaluate and Prepocess Data

In [ ]:
import seaborn as sns

df = sns.load_dataset('diamonds')

df.shape

(53940, 10)

In [ ]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [ ]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [ ]:
class_mapper = {'Ideal':1,'Premium':2,'Very Good':3,'Good':4,'Fair':5}
df['cut']=df['cut'].replace(class_mapper)

/root/.ipykernel/1411/command-7828683756956319-3517931333:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['cut']=df['cut'].replace(class_mapper)
/root/.ipykernel/1411/command-7828683756956319-3517931333:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['cut']=df['cut'].replace(class_mapper)

In [ ]:
class_mapper_color = {'G':1,'E':2,'F':3,'H':4,'D':5,'I':6, 'J':7}
df['color']=df['color'].replace(class_mapper_color)

/root/.ipykernel/1411/command-7828683756956320-3616300415:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['color']=df['color'].replace(class_mapper_color)
/root/.ipykernel/1411/command-7828683756956320-3616300415:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['color']=df['color'].replace(class_mapper_color)

In [ ]:
class_mapper_clarity = {'SI1':1,'VS2':2,'SI2':3,'VS1':4,'VVS2':5,'VVS1':6, 'IF':7, 'I1':8}
df['clarity']=df['clarity'].replace(class_mapper_clarity)

/root/.ipykernel/1411/command-7828683756956321-3993500978:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['clarity']=df['clarity'].replace(class_mapper_clarity)
/root/.ipykernel/1411/command-7828683756956321-3993500978:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['clarity']=df['clarity'].replace(class_mapper_clarity)

In [ ]:
df.head(10)

   carat cut color clarity  depth  table  price     x     y     z
0   0.23   1     2       3   61.5   55.0    326  3.95  3.98  2.43
1   0.21   2     2       1   59.8   61.0    326  3.89  3.84  2.31
2   0.23   4     2       4   56.9   65.0    327  4.05  4.07  2.31
3   0.29   2     6       2   62.4   58.0    334  4.20  4.23  2.63
4   0.31   4     7       3   63.3   58.0    335  4.34  4.35  2.75
5   0.24   3     7       5   62.8   57.0    336  3.94  3.96  2.48
6   0.24   3     6       6   62.3   57.0    336  3.95  3.98  2.47
7   0.26   3     4       1   61.9   55.0    337  4.07  4.11  2.53
8   0.22   5     2       2   65.1   61.0    337  3.87  3.78  2.49
9   0.23   3     4       4   59.4   61.0    338  4.00  4.05  2.39

### Step 1. Use RandomForestRegressor to Train and Predict the Diamond Price (19%)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
# your code here

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
print(df.dtypes)

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [ ]:
# df_numeric_ftrs = df.select_dtypes(include=['float64','int64'])

In [ ]:
# df_numeric_ftrs.head(10)

In [ ]:
Y = df.iloc[:, df.columns.get_loc('price')]
X = df.loc[:, df.columns != 'price']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf = RandomForestRegressor(n_estimators=8)
rf.fit(X_train, Y_train)

RandomForestRegressor(n_estimators=8)

### Step 2. Evaluate the Model's Performance (1%)

In [ ]:
from sklearn import metrics

In [ ]:
# your code here

In [ ]:
Y_pred = rf.predict(X_test)

In [ ]:
rfr_score_without_optimization = metrics.r2_score(Y_test,Y_pred)
print(rfr_score_without_optimization)

0.979564714634784

In [ ]:
# Print the default hyperparameters used by the RandomForestRegressor
print(rf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 8, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

## Step 3. Optimize the Model with GridSearchCV (30%)

Use the notebook lesson "Grid Search CV" as an example how to use GridSearchCV to optimize RandomForestRegressor. You will create your search space and experiment, so the final result should be better than the one shown in Step 2.

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit

In [ ]:
# your code here

In [ ]:
cv = ShuffleSplit(n_splits=2, test_size=0.3, random_state=0)

In [ ]:
rf_parameters = {} #an empty dict signifies default parameters

rf_opt = GridSearchCV(RandomForestRegressor(),
                  param_grid=rf_parameters,
                  cv=cv,            
                  return_train_score=True)

In [ ]:
result = rf_opt.fit(X_train, Y_train)

In [ ]:
result.best_params_

{}

In [ ]:
Y_pred = rf_opt.predict(X_test)

In [ ]:
rfr_score_with_optimization_empty_param_grid = metrics.r2_score(Y_test,Y_pred)
print(rfr_score_with_optimization_empty_param_grid)

0.9808827694376753

In [ ]:
print(rfr_score_without_optimization)
print(rfr_score_with_optimization_empty_param_grid)

0.979564714634784
0.9808827694376753

Mild improvement with default parameters.

In [ ]:
'''
rf_parameters = {
    'n_estimators': [2, 3, 4],
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'random_state': [0, 1],
    'max_depth': [2, 3],
}


rf_parameters = {
    'n_estimators': [2, 3, 4, 5],
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'random_state': [0, 1, 2],
    'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
}
'''
rf_parameters = {
    'n_estimators': [10, 13, 16, 19],
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'random_state': [1,2],
    'max_depth': [6, 8, 10, 12],
}

'''
rf_parameters = {
    'n_estimators': [2, 3, 4, 5],
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'random_state': [0, 1, 2]
}

rf_parameters = {
    'max_features':[0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95],
    'n_estimators': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'random_state': [0, 1, 2]
}
'''

"\nrf_parameters = {\n    'n_estimators': [2, 3, 4, 5],\n    'criterion': ['squared_error', 'absolute_error', 'poisson'],\n    'random_state': [0, 1, 2]\n}\n\nrf_parameters = {\n    'max_features':[0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95],\n    'n_estimators': [2, 3, 4, 5, 6, 7, 8, 9, 10],\n    'criterion': ['squared_error', 'absolute_error', 'poisson'],\n    'random_state': [0, 1, 2]\n}\n"

In [ ]:
print(rf_parameters)

{'n_estimators': [10, 13, 16, 19], 'criterion': ['squared_error', 'absolute_error', 'poisson'], 'random_state': [1, 2], 'max_depth': [6, 8, 10, 12]}

In [ ]:
rf_opt_grid = GridSearchCV(RandomForestRegressor(),
                  param_grid=rf_parameters,
                  cv=cv,            
                  return_train_score=True)

In [ ]:
result = rf_opt_grid.fit(X_train, Y_train)

In [ ]:
result.best_params_

{'criterion': 'squared_error',
 'max_depth': 12,
 'n_estimators': 19,
 'random_state': 1}

In [ ]:
Y_pred_opt = rf_opt_grid.predict(X_test)

In [ ]:
rfr_score_with_optimization = metrics.r2_score(Y_test,Y_pred_opt)
print(rfr_score_with_optimization)

0.9794146892775313

In [ ]:
print(rfr_score_without_optimization)
print(rfr_score_with_optimization)
print(rfr_score_with_optimization_empty_param_grid)

0.979564714634784
0.9794146892775313
0.9808827694376753

The default values had the best performance.
The without opimisation is very close to and sligtly better than the optimised returned by grid search. The parameter grid must be too restrictive.